### PR TITLE
Update

### PR DESCRIPTION
**Pull request by jasperan**

### CODE REVIEW

**Review by ttscoff — COMMENTED** [review]
Are we supposed to include OCIDs in our repos?

**Comment by jasperan** [comment]
Not in general @ttscoff but these are LLM model OCIDs, required to run the demo. These OCIDs are always the same across regions and necessary to invoke these models

**Comment by jasperan** [comment]
@ttscoff could you approve / reject the PR?

**Review by ttscoff — APPROVED** [review]

**Comment by ttscoff** [comment]
Sorry, the review needed to be re-requested. Approved.

**Pull request merged**
